### ISSUE TITLE
Option listed as 'sortBy' but reference in code 'sortby'

### ISSUE THREAD

**Issue by bsheen** [pastgift/sorted-json-js#3]
Hi,

As per the issue title the instructions in readme.md and code do not align. Option listed as 'sortBy' in the instructions but reference in code 'sortby'.

Cheers,
Brendt

**Comment by pastgift** [comment]
You are right, it's my mistake.
I have fixed it. please check it out.

**Comment by bsheen** [comment]
Looks good to me. Thanks for sorting this so promptly!
