### ISSUE TITLE
sortify does not work on node 10.12.0+ due to null sort function

### ISSUE THREAD

**Issue by gdspicer58** [pastgift/sorted-json-js#5]
While using this function, I ran into the following error when passing nothing into options
![Screen Shot 2019-06-17 at 5 18 31 PM](https://user-images.githubusercontent.com/51673884/59640606-36750680-9124-11e9-9c2c-2ad0906fa179.png)

This wasn't happening when I was on node 8 but does now appear on node 10

I think you can change

sortBy: null

to

sortBy: undefinded

in DEFAULT_SORT_OPTIONS to fix this, but figured it would be something you want to be aware of

**Comment by pastgift** [comment]
You are right!
I fixed it in version 0.2.6, Thank you for your feedback!
